### ISSUE TITLE
Export function not working.

### ISSUE THREAD

**Issue by Ninji-X** [Stvad/CrowdAnki#113]
When I try to export, I get the following error:

```Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.37 (6d596c8f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-18 15:34:33

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1114, in onExport
  File "aqt\exporting.py", line 33, in __init__
  File "aqt\exporting.py", line 48, in setup
  File "<decorator-gen-2>", line 2, in exporterChanged
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1788670778\anki\overrides\exporting.py", line 17, in exporter_changed
    self.exporter = aqt.exporting.exporters()[exporter_id][1](self.col)
TypeError: exporters() missing 1 required positional argument: 'col'
```

The only addon I have installed is CrowdAnki.

**Comment by aplaice** [comment]
Thanks very much for reporting the bug!

Anki's code changed between 2.1.35 and 2.1.36 such that the `exporters()` method required an argument (`col`) — as the error message stated.

As this is a very simple fix, you can (if you want to!) apply it yourself — in `C:\Users\Username\AppData\Roaming\Anki2\addons21\1788670778\anki\overrides\exporting.py` on line 17, change:

```python
    self.exporter = aqt.exporting.exporters()[exporter_id][1](self.col)
```

to:

```python
    self.exporter = aqt.exporting.exporters(self.col)[exporter_id][1](self.col)
```

(i.e. add `self.col`). Alternatively, you can wait for a new `CrowdAnki` release, which will hopefully be relatively soon (but which is beyond my control).
