### ISSUE TITLE
Addon crashes on import from disk

### ISSUE THREAD

**Issue by simgunz** [Stvad/CrowdAnki#217]
Steps to reproduce:
- Download and extract the [Ultimate Geography deck](https://github.com/anki-geo/ultimate-geography/releases/download/v5.2/Ultimate_Geography_v5.2_EN.zip)
- Click File > CrowdAnki: Import from disk

Error:
```
Anki 24.06.3 (d678e393) (src) (ao)
Python 3.12.6 Qt 6.7.2 PyQt 6.7.1
Platform: Linux-6.10.13-3-MANJARO-x86_64-with-glibc2.40

Traceback (most recent call last):
  File "/media/data/software/anki/profiles/addons21/crowd-anki/anki/ui/action_vendor.py", line 32, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/anki_importer.py", line 112, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/anki_importer.py", line 101, in import_deck_from_path
    if importer.load_deck(directory_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/anki_importer.py", line 31, in load_deck
    import_config = self.read_import_config(directory_path, deck_json)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/anki_importer.py", line 91, in read_import_config
    import_dialog = ImportDialog(deck_json, import_dict)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/import_dialog.py", line 78, in __init__
    self.ui_initial_setup()
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/import_dialog.py", line 87, in ui_initial_setup
    self.setup_personal_field_selection()
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/import_dialog.py", line 113, in setup_personal_field_selection
    add_header(model_name)
  File "/media/data/software/anki/profiles/addons21/crowd-anki/importer/import_dialog.py", line 98, in add_header
    heading_ui.setFlags(Qt.ItemIsEnabled)
                        ^^^^^^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'ItemIsEnabled'
```

**Comment by aplaice** [comment]
Thanks for reporting!

However, do you have the latest CrowdAnki?  I believe that this should already be fixed in the current version. See:

https://github.com/Stvad/CrowdAnki/blob/force_media_sync_on_import/crowd_anki/importer/import_dialog.py#L98

which now has `Qt.ItemFlag.ItemIsEnabled`.  Downloading from ankiweb with Anki 24.06 I seem to get the current (fixed) version of CrowdAnki.

**Comment by simgunz** [comment]
Hi, thanks for the answer.

I checked for updates from the addon page and the reply was that no updates are available (tried again today, same result).

Though uninstalling and reinstalling the add-on solved the problem.

**Comment by aplaice** [comment]
Thanks for checking! That's weird — I have no idea why ankiweb did not show the update.
