### ISSUE TITLE
Github security updates have broken crowdanki

### ISSUE THREAD

**Issue by dawch** [Stvad/CrowdAnki#25]
When trying to import from my github anki deck I get the following notice: 

Error while trying to get deck from Github: <urlopen error [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>

and error message: 
\An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Anki2/addons/crowd_anki/main.py", line 31, in <lambda>
    github_import_action.triggered.connect(lambda : GithubImporter.on_github_import_action(mw.col))
  File "/Users/chris/Library/Application Support/Anki2/addons/crowd_anki/github/github_importer.py", line 29, in on_github_import_action
    github_importer.import_from_github()
  File "/Users/chris/Library/Application Support/Anki2/addons/crowd_anki/github/github_importer.py", line 44, in import_from_github
    self.download_and_import(repo)
  File "/Users/chris/Library/Application Support/Anki2/addons/crowd_anki/github/github_importer.py", line 48, in download_and_import
    response = urllib2.urlopen(GITHUB_LINK.format(repo))
  File "urllib2.pyc", line 127, in urlopen
  File "urllib2.pyc", line 404, in open
  File "urllib2.pyc", line 422, in _open
  File "urllib2.pyc", line 382, in _call_chain
  File "urllib2.pyc", line 1222, in https_open
  File "urllib2.pyc", line 1184, in do_open
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>

This appears to be caused by a github update:  https://githubengineering.com/crypto-removal-notice/

**Comment by Stvad** [comment]
apparently, this is solved by updating your python/openssl.

**Comment by dawch** [comment]
It looks like trying to do either of those things is going to be non-trivial, at least on my system (Mac OS X 10.11.6)

**Comment by Stvad** [comment]
A current version of the error
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.9 (ae67c976) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.3
Flags: frz=True ao=True sv=1
Add-ons possibly involved: 1788670778

Caught exception:
  File "/Users/sitalov/Library/Application Support/Anki2/addons21/1788670778/main.py", line 31, in <lambda>
    github_import_action.triggered.connect(lambda : GithubImporter.on_github_import_action(mw.col))
  File "/Users/sitalov/Library/Application Support/Anki2/addons21/1788670778/github/github_importer.py", line 28, in on_github_import_action
    github_importer.import_from_github()
  File "/Users/sitalov/Library/Application Support/Anki2/addons21/1788670778/github/github_importer.py", line 34, in import_from_github
    self.download_and_import(repo)
  File "/Users/sitalov/Library/Application Support/Anki2/addons21/1788670778/github/github_importer.py", line 38, in download_and_import
    response = urlopen(GITHUB_LINK.format(repo))
  File "urllib/request.py", line 223, in urlopen
  File "urllib/request.py", line 526, in open
  File "urllib/request.py", line 544, in _open
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 1361, in https_open
  File "urllib/request.py", line 1320, in do_open
<class 'urllib.error.URLError'>: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
```

**Comment by Stvad** [comment]
I believe it's hitting problem described here: https://stackoverflow.com/a/42334357/1114790 
Anki seems to be packing its own version of Python though, so installing `certifi` for system Python does not help.   
One potential thing here is to disable certificate verification, but it does not feel like a great solution to me =\

**Comment by Stvad** [comment]
This should be fixed now that we directly work with git vs github
