### ISSUE TITLE
Error when deck name includes non-ASCII characters

### ISSUE THREAD

**Issue by evolverine** [Stvad/CrowdAnki#30]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
```
  File "aqt\exporting.py", line 116, in accept
  File "C:\Users\evolverine\Documents\Anki\addons\crowd_anki\anki_exporter_wrapper.py", line 37, in exportInto
    self.anki_json_exporter.export_deck_to_directory(deck_name, Path(directory_path).parent, self.includeMedia)
  File "C:\Users\evolverine\Documents\Anki\addons\crowd_anki\anki_exporter.py", line 50, in export_deck_to_directory
    self._copy_media(deck, deck_directory)
  File "C:\Users\evolverine\Documents\Anki\addons\crowd_anki\anki_exporter.py", line 71, in _copy_media
    str(media_directory.resolve()))
  File "shutil.py", line 116, in copy
  File "ntpath.py", line 108, in join
    If the path contained a UNC path, the drive_or_unc will contain the host name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 67: ordinal not in range(128)
```

**Comment by evolverine** [comment]
I'm working on this now, hopefully will have a fix soon.

**Comment by Stvad** [comment]
I thought this one was fixed for a while =\. What version of Anki/addon/OS do you have?

**Comment by Stvad** [comment]
tested this working on a recent version of plugin/Anki, please let me know if it re-occurs
