### ISSUE TITLE
Export error - character maps 

### ISSUE THREAD

**Issue by ChristianKleineidam** [Stvad/CrowdAnki#4]
"Species Taxonomy" deck
___________________________
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.exporting", line 108, in accept
  File "C:\Users\myuser\Documents\Anki\addons\crowd_anki\anki_exporter_wrapper.py", line 35, in exportInto
    self.anki_json_exporter.export_deck_to_directory(deck_name, Path(directory_path).parent, self.includeMedia)
  File "C:\Users\myuser\Documents\Anki\addons\crowd_anki\anki_exporter.py", line 26, in export_deck_to_directory
    ensure_ascii=False)))
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/encodings.cp1252", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3430-3433: character maps to <undefined>
_______________________________

**Comment by Stvad** [comment]
Can you please provide a deck that I can use to reproduce this one?

**Comment by ChristianKleineidam** [comment]
I sent you the deck via email.
