### ISSUE TITLE
Error while importing deck into anki via CrowdAnki

### ISSUE THREAD

**Issue by learnwell** [Stvad/CrowdAnki#97]
Thank you for writing this plugin.

Here are the steps that led to the error log posted below:
1. I exported my deck using CrowdAnki
2. I pushed it to a github repo
3. I downloaded and unzipped the very same deck from github
4. I attempted to import the deck using CrowdAnki

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-25 14:08:58
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 112, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 101, in import_deck_from_path
    if importer.load_deck(directory_path):
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/importer/anki_importer.py", line 39, in load_deck
    deck.save_to_collection(self.collection, import_config=import_config)
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/representation/deck.py", line 131, in save_to_collection
    self.save_decks_and_notes(collection=collection,
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/representation/deck.py", line 154, in save_decks_and_notes
    note.save_to_collection(collection, self, model_map_cache, import_config=import_config)
  File "/Users/training/Library/Application Support/Anki2/addons21/1788670778/representation/note.py", line 125, in save_to_collection
    self.anki_object.flush()
  File "anki/notes.py", line 67, in flush
AssertionError
```

**Comment by aplaice** [comment]
Thanks for reporting the bug!

Unfortunately, `CrowdAnki` isn't yet compatible with the latest Anki, due to changes in Anki's internals, which `CrowdAnki` depends on.

As a workaround, you can (temporarily) downgrade to the previous stable Anki release (2.1.26). To do that, in your current version of Anki, you first need to go to File > Switch Profile > Downgrade & Quit (in the lower right). You can then run the older Anki version, and import the CrowdAnki deck. (You don't need to do anything special before upgrading back.) Obviously, switching between versions isn't very convenient if you're planning to import and export the deck several times...

(AFAICT it's the same error message and bug, as #92.)

**Comment by learnwell** [comment]
Thank you for explaining the situation and workaround 👍
